# TODO: uncomment
# FROM ghcr.io/foliant-docs/foliant/foliant:latest
FROM docker.io/foliant/foliant:latest

# RUN apt-get update && \
#     apt-get install -y \
#         wget \
#         texlive-full \
#         texlive-latex-extra \
#     && apt-get clean \
#     && rm -rf /var/lib/apt/lists/*

# RUN tlmgr update --self && \
#     tlmgr install tocstyle && \
#     mktexlsr

# RUN apt-get update && apt-get install -y \
#     python3.11 \
#     python3-pip \
#     texlive-latex-base \
#     texlive-latex-extra \
#     texlive-fonts-recommended \
#     texlive-fonts-extra \
#     texlive-lang-cyrillic \
#     texlive-science \
#     && rm -rf /var/lib/apt/lists/*
RUN apt update && apt install -y wget texlive-full librsvg2-bin

RUN wget https://github.com/jgm/pandoc/releases/download/3.1.12.2/pandoc-3.1.12.2-1-amd64.deb && dpkg -i pandoc-3.1.12.2-1-amd64.deb
RUN pip3 install foliantcontrib.pandoc
