FROM ghcr.io/foliant-docs/foliant/foliant:1.0.14-pandoc

RUN apt update \
    && apt install --reinstall ca-certificates \
    && apt install -y \
    # Needed for ImageMagick
    inkscape \
    # Needed for Puppeteer
    libasound2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ./dependency_files/ /usr/src/app/dependency_files/

RUN rm -rf /etc/ImageMagick-6/policy.xml \
    && cp /usr/src/app/dependency_files/imagemagick/policy.xml /etc/ImageMagick-6/

RUN wget -q -O - https://deb.nodesource.com/setup_20.x | bash
RUN apt install -y nodejs

# Uncomment on the next line and comment on the previous one if your region has problems accessing deb.nodesource.com
# RUN curl -fsSL https://nodejs.org/dist/v20.18.0/node-v20.18.0-linux-x64.tar.xz -o node.tar.xz && \
#     tar -xJf node.tar.xz -C /usr/local --strip-components=1 && \
#     rm node.tar.xz

ENV PATH=/usr/local/bin:$PATH

RUN npm install -g puppeteer \
    # Needed for BPMN preprocessor
    && npm install -g bpmn-to-image@0.5.1 --unsafe-perm \
    # Needed for Argdown preprocessor
    && npm install -g @argdown/cli \
    && npm install -g @argdown/image-export --unsafe-perm

#######################
# Databases for DBDoc #
#######################

# MS SQL Server
RUN apt-get update && \
    apt-get install -y curl gnupg && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql17

# MySQL
RUN apt-get install -y mysql-server libmysqlclient-dev

#######################

RUN npm install -g widdershins \
    mermaid \
    && npm install -g mermaid.cli --unsafe-perm=true --allow-root \
    && npm install -g aglio --unsafe-perm=true --allow-root \
    && npm install -g md-to-pdf --unsafe-perm=true --allow-root \
    && npm install -g raml2html raml2html-full-markdown-theme

RUN mkdir -p /usr/src/app/dependency_files/slate/ \
    && cd /usr/src/app/dependency_files/slate/ \
    && wget -O ./Gemfile https://raw.githubusercontent.com/slatedocs/slate/main/Gemfile \
    && wget -O ./Gemfile.lock https://raw.githubusercontent.com/slatedocs/slate/main/Gemfile.lock \
    && apt install -y zlib1g-dev ruby-full \
    && gem install bundler -v 2.4.22 \
    && bundle install

# Needed for Confluence backend
RUN apt install -y \
    libkrb5-dev \
    graphviz \
    libgraphviz-dev \
    plantuml \
    && wget -O /usr/share/plantuml/plantuml.jar http://sourceforge.net/projects/plantuml/files/plantuml.jar/download \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV PLANTUML_LIMIT_SIZE=100000

RUN pip3 install --upgrade pip \
    && cd /usr/src/app/dependency_files/python_packages/ \
    && pip3 install -r ./requirements.txt \
    && pip3 install --no-compile -r ./requirements_no_compile.txt

WORKDIR /usr/src/app/
