FROM foliant/foliant

ENV DEBIAN_FRONTEND noninteractive
RUN apt update && apt install -y wget texlive-full librsvg2-bin
RUN wget https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb && \
    dpkg -i pandoc-2.7.2-1-amd64.deb
RUN pip3 install foliantcontrib.pandoc
