FROM ubuntu:rolling

RUN apt update && apt install -y wget git python3 python3-pip
RUN wget https://github.com/jgm/pandoc/releases/download/2.0.5/pandoc-2.0.5-1-amd64.deb && \
    dpkg -i pandoc-2.0.5-1-amd64.deb
RUN pip3 install -U pip \
    git+https://github.com/foliant-docs/foliant.git@nextgen
RUN apt install -y locales && locale-gen en_US.UTF-8

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

ENTRYPOINT [ "foliant" ]
