# TODO: uncomment
FROM ghcr.io/foliant-docs/foliant/foliant

RUN apt update && apt install -y wget texlive-full librsvg2-bin

RUN wget https://github.com/jgm/pandoc/releases/download/3.1.12.2/pandoc-3.1.12.2-1-amd64.deb && dpkg -i pandoc-3.1.12.2-1-amd64.deb
RUN pip3 install foliantcontrib.pandoc
