FROM ubuntu:24.04

LABEL authors="Konstantin Molchanov <moigagoo@live.com>"

ARG VERSION
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    curl \
    git \
    python3-full \
    pip

RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip3 install poetry

# TODO: make install from PyPi
RUN git clone -b add-partial-copy https://github.com/foliant-docs/foliant.git \
    && cd foliant \
    && poetry build --format=wheel \
    && pip3 install dist/*.whl 

RUN apt-get install -y locales && locale-gen en_US.UTF-8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

ENTRYPOINT [ "foliant" ]
CMD []
