FROM foliant/pandoc

RUN apt update; apt install -y git python3 python3-pip
RUN pip3 install -U pip \
    git+https://github.com/foliant-docs/foliant.git@nextgen \
    git+https://github.com/foliant-docs/foliantcontrib.pandoc.git@develop

ENTRYPOINT foliant
