FROM ubuntu:focal

LABEL authors="Konstantin Molchanov <moigagoo@live.com>"

ARG VERSION

RUN apt update && apt install -y git python3 python3-pip
RUN pip3 install foliant>=$VERSION

RUN apt install -y locales && locale-gen en_US.UTF-8
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

ENTRYPOINT [ "foliant" ]
CMD []
